source "https://rubygems.org"

gem "jekyll", "~> 4.3"

group :jekyll_plugins do
  gem "jekyll-seo-tag"
  gem "jekyll-feed"
  gem "jekyll-paginate-v2"
  gem "jekyll-sitemap"
end

gem "purelog", path: "../theme"
